import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { describe, expect, it } from 'vitest';

const SOURCE_ROOTS = ['app', 'components'];

// Files exempt from the visual-debt scan. `app/opengraph-image.tsx` is rendered
// by Satori (next/og), which only understands inline styles + literal hex colors
// — Tailwind design tokens don't exist in that runtime — so its hex/inline-style
// usage is structural, not debt. (components/ui/ is exempted separately below.)
const VISUAL_DEBT_EXEMPT_FILES = new Set<string>();

const VISUAL_DEBT_BASELINE = {
  arbitraryShadow: 0,
  // 2026-06-10 release audit: all-caps label tracking unified onto the
  // --tracking-label / --tracking-display tokens (0 arbitrary values left)
  // and studio text sizes moved onto the type-scale tokens; the remaining
  // arbitrary text sizes are landing-mockup prose + the 404 display numeral.
  arbitraryText: 2,
  arbitraryTracking: 0,
  // 2026-06-25 UI/UX audit: +4 semantic token definitions in globals.css
  // (--book-info-light/-border, --book-on-gold light+dark) — design-system
  // growth, not component debt. Dark info-light/-border use rgba (+2).
  hexColor: 70,
  // 2026-06-26 workshop roadmap: +5 from the command-center dashboard's
  // data-driven viz — stacked trend-bar fills + the progress ring/bar widths
  // are runtime-dynamic dimensions Tailwind JIT cannot generate as classes, so
  // inline style is the canonical path (not careless hardcoding).
  // 2026-07-02 UI/UX audit: −1, removed a dead `style={{}}` no-op passed to the
  // manuscript flipbook (ManuscriptReadingView).
  // 2026-07-02 prelaunch cleanup: −1, removed the deleted vault migration dialog.
  // 2026-07-03 dead-code(batchC): −5, removed the unmounted command-center
  // dashboard whose data-driven viz (trend-bar fills + progress ring/bar
  // widths) owned this entire bucket.
  // 2026-07-21 stage-bar redesign: the single stage-surface dynamic width
  // moved from StageActionPill (deleted popover) to StageBar's progress
  // track — same justification, same count.
  inlineStyle: 6,
  rgba: 22,
} as const;

// Bare Tailwind palette utilities (e.g. bg-red-500, text-zinc-400) are forbidden
// in business UI — color must come from semantic --book-* tokens. The book-*
// tokens are safe because "book" sits between the prefix and the palette word
// (bg-book-violet never matches `bg-violet-N`). Vendored assistant-ui surfaces
// are exempt: they're regenerated by the assistant-ui CLI and ship their own
// prose theming.
const NAMED_PALETTE_PATTERN =
  /\b(?:bg|text|border|ring|from|to|via|fill|stroke|divide|outline|decoration|placeholder)-(?:red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose|slate|gray|zinc|neutral|stone)-\d/g;
const NAMED_PALETTE_EXEMPT_PREFIXES = ['components/assistant-ui/'];

const FORBIDDEN_PATTERNS: ReadonlyArray<[RegExp, string]> = [
  [/<button\b|<\/button>/, 'raw button'],
  [/<input\b/, 'raw input'],
  [/<select\b|<\/select>/, 'raw select'],
  [/<textarea\b|<\/textarea>/, 'raw textarea'],
  [/<details\b|<\/details>|<summary\b|<\/summary>/, 'raw disclosure'],
  [/role=["'](?:button|dialog|tab|tablist|listbox|option|radio|radiogroup)["']/, 'hand-rolled ARIA primitive'],
  [/from ["'](?:@radix-ui\/react-[^"']+|radix-ui)["']/, 'direct Radix import'],
  [/intentional raw|raw </, 'raw-control escape comment'],
];

function collectTsxFiles(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    const rel = relative(process.cwd(), path);
    if (rel.startsWith('components/ui/')) continue;
    const stat = statSync(path);
    if (stat.isDirectory()) {
      out.push(...collectTsxFiles(path));
    } else if (path.endsWith('.tsx') && !path.endsWith('.test.tsx')) {
      // Test files assert against rendered markup (e.g. locating a `<button`
      // tag in renderToStaticMarkup output), which is not a hand-rolled
      // control — the contract guards business UI surfaces only.
      out.push(path);
    }
  }
  return out;
}

// Motion is a repo-wide contract, including the primitive layer that the
// general business-UI collector intentionally excludes.
function collectMotionTsxFiles(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    const stat = statSync(path);
    if (stat.isDirectory()) {
      out.push(...collectMotionTsxFiles(path));
    } else if (path.endsWith('.tsx') && !path.endsWith('.test.tsx')) {
      out.push(path);
    }
  }
  return out;
}

function collectMotionSourceFiles(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    const stat = statSync(path);
    if (stat.isDirectory()) {
      out.push(...collectMotionSourceFiles(path));
    } else if ((path.endsWith('.tsx') && !path.endsWith('.test.tsx')) || path.endsWith('.css')) {
      out.push(path);
    }
  }
  return out;
}

const MOTION_FORBIDDEN_PATTERNS: ReadonlyArray<[RegExp, string]> = [
  [/\btransition-all\b/g, 'transition-all'],
  [/\banimate-\[/g, 'arbitrary animation'],
  [/\bduration-\d+\b/g, 'literal duration utility'],
  [/\bease-(?:in-out|in|out|linear)\b/g, 'built-in easing utility'],
  [/\banimate-(?:in|out)\b/g, 'tailwindcss-animate lifecycle utility'],
  [/\b(?:fade|zoom)-(?:in|out)-\d+\b/g, 'tailwindcss-animate fade/zoom utility'],
  [/\bslide-(?:in-from|out-to)-[^\s"'`}]+/g, 'tailwindcss-animate slide utility'],
];

const SPINNER_FILE = 'components/ui/spinner.tsx';

function collectUiSourceFiles(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    const rel = relative(process.cwd(), path);
    if (rel.startsWith('components/ui/')) continue;
    if (VISUAL_DEBT_EXEMPT_FILES.has(rel)) continue;
    const stat = statSync(path);
    if (stat.isDirectory()) {
      out.push(...collectUiSourceFiles(path));
    } else if (path.endsWith('.tsx') || path.endsWith('.css')) {
      out.push(path);
    }
  }
  return out;
}

const VISUAL_DEBT_PATTERNS: ReadonlyArray<[keyof typeof VISUAL_DEBT_BASELINE, RegExp]> = [
  ['hexColor', /#[0-9a-fA-F]{3,8}\b/g],
  ['rgba', /rgba\(/g],
  ['arbitraryText', /(?:^|\s)(?:[a-z:![\]_-]+:)*text-\[[^\]]+\]/g],
  ['arbitraryTracking', /(?:^|\s)(?:[a-z:![\]_-]+:)*tracking-\[[^\]]+\]/g],
  ['arbitraryShadow', /(?:^|\s)(?:[a-z:![\]_-]+:)*shadow-\[[^\]]+\]/g],
  ['inlineStyle', /style=\{\{/g],
];

// ── Design-drift invariants (2026-07-14 convergence) ────────────────────────
//
// The shape of a clickable control is decided by its semantic role, not by the
// call site. Business <Button> tags therefore carry no radius utility at all —
// they inherit the canonical Button radius. Primitive definitions are excluded
// from the scan, and one business-level structural exception exists:
//   1. components/ui/ — where semantic primitives (e.g. the round page-turn
//      control) are *defined*. Already excluded from every scan below.
//   2. The collapsed stage pill, whose product role IS a status pill/toggle.
//      It lives in StageBar, the persistent stage strip that replaced the old
//      floating popover entry point.
const RADIUS_PATTERN = /\brounded-(?:none|xs|sm|md|lg|xl|2xl|3xl|full|\[[^\]]+\])/;
const RADIUS_EXCEPTION_ATTR = 'data-shape="stage-pill"';
const RADIUS_EXCEPTION_FILE = 'components/StageBar.tsx';

const PAGE_TURN_PRIMITIVE = '@/components/ui/page-turn-button';
const PAGE_TURN_SURFACES = [
  'components/ManuscriptReadingView.tsx',
];
// The duplicated control both surfaces used to hand-roll: a 36px circle on the
// card background. Only the primitive may express it.
const PAGE_TURN_SIGNATURE = /h-9 w-9[^"'`]*rounded-full|rounded-full[^"'`]*h-9 w-9/;

const EMPTY_PRIMITIVE = '@/components/ui/empty';
const EMPTY_STATE_SURFACES = [
  'components/conversations/ConversationList.tsx',
  'components/conversations/ConversationThread.tsx',
  'components/studio/usage-panel.tsx',
  'components/knowledge/KnowledgePanel.tsx',
  'components/EmptyChatInterviewGuide.tsx',
  'components/ManuscriptReadingView.tsx',
];
const EMPTY_DENSITY_CONTRACTS: Readonly<Record<string, readonly string[]>> = {
  'components/conversations/ConversationList.tsx': ['p-0', 'px-3', 'py-8', 'md:p-0', 'md:px-3', 'md:py-8'],
  'components/conversations/ConversationThread.tsx': ['p-0', 'py-12', 'md:p-0', 'md:py-12'],
  'components/studio/usage-panel.tsx': ['p-0', 'md:p-0'],
  'components/knowledge/KnowledgePanel.tsx': ['p-0', 'py-12', 'md:p-0', 'md:py-12'],
  'components/EmptyChatInterviewGuide.tsx': ['p-0', 'px-6', 'py-12', 'md:p-0', 'md:px-6', 'md:py-12'],
  'components/ManuscriptReadingView.tsx': ['p-10', 'md:p-12'],
};

/**
 * Extracts JSX opening tags for `name`, tolerating arrows, nested braces,
 * strings and comments inside the tag (`onClick={() => …}`, `// it's fine`).
 */
function openingTags(src: string, name: string): string[] {
  const out: string[] = [];
  const re = new RegExp(`<${name}(?![A-Za-z0-9_])`, 'g');
  let match: RegExpExecArray | null;
  while ((match = re.exec(src))) {
    let i = match.index + match[0].length;
    let depth = 0;
    for (; i < src.length; i++) {
      const c = src[i];
      if (c === '"' || c === "'" || c === '`') {
        const quote = c;
        for (i++; i < src.length && src[i] !== quote; i++) if (src[i] === '\\') i++;
        continue;
      }
      if (c === '/' && src[i + 1] === '/') {
        while (i < src.length && src[i] !== '\n') i++;
        continue;
      }
      if (c === '/' && src[i + 1] === '*') {
        i = src.indexOf('*/', i + 2);
        if (i < 0) return out;
        i++;
        continue;
      }
      if (c === '{') depth++;
      else if (c === '}') depth--;
      else if (c === '>' && depth === 0) break;
    }
    out.push(src.slice(match.index, i + 1));
  }
  return out;
}

/** Opening tag + children, so a rule can assert on what a control renders. */
function elements(src: string, name: string): string[] {
  let cursor = 0;
  return openingTags(src, name).map(tag => {
    const start = src.indexOf(tag, cursor);
    if (start < 0) return tag;
    const close = src.indexOf(`</${name}>`, start + tag.length);
    cursor = close < 0 ? start + tag.length : close + `</${name}>`.length;
    return close < 0 ? tag : src.slice(start, close);
  });
}

/** Inlines `className={CONST}` / `${CONST}` so a class constant can't launder a radius. */
function classSources(tag: string, src: string): string {
  let resolved = tag;
  for (const [, ident] of tag.matchAll(/(?:className=\{|\$\{)([A-Za-z_$][\w$]*)[}\s]/g)) {
    const decl = src.match(new RegExp(`const\\s+${ident}\\s*(?::[^=]+)?=\\s*([\\s\\S]*?);`));
    resolved += decl ? decl[1] : ` __unresolved_class_source:${ident}`;
  }
  return resolved;
}

/** Order-independent signature for the pre-convergence centered empty wrapper. */
function hasAdHocEmptyWrapper(src: string): boolean {
  const required = ['flex', 'flex-col', 'items-center', 'justify-center', 'text-center'];
  return openingTags(src, 'div').some(tag => {
    const classes = classSources(tag, src);
    return required.every(token => new RegExp(`(?:^|\\s)${token}(?:\\s|$)`).test(classes));
  });
}

function hasClassTokens(tag: string, src: string, required: readonly string[]): boolean {
  const tokens = new Set(classSources(tag, src).match(/[-A-Za-z0-9:[\]_/\.]+/g) ?? []);
  return required.every(token => tokens.has(token));
}

const LEGACY_PRODUCT_PATTERNS: ReadonlyArray<[RegExp, string]> = [
  [/href=["']\/login["']|router\.push\(["']\/login["']\)/i, 'hosted login route'],
  [/\bcredits?\b/i, 'platform credits'],
  [/\bstripe\b/i, 'Stripe UI'],
  [/SupabaseAuthProvider/, 'Supabase auth UI provider'],
  [/\bsign[- ]?in\b/i, 'sign-in UI copy'],
  [/pricing(?:Page|Card|Tier)|href=["']\/pricing|router\.push\(["']\/pricing|pricing\s+(?:plan|tier)/i, 'SaaS pricing surface'],
  [/platform-models|gateway-models/i, 'platform model surface'],
];

describe('business UI uses design-system primitives', () => {
  it('keeps app and component surfaces off hand-rolled interactive controls', () => {
    const violations: string[] = [];

    for (const root of SOURCE_ROOTS) {
      for (const file of collectTsxFiles(join(process.cwd(), root))) {
        const rel = relative(process.cwd(), file);
        const src = readFileSync(file, 'utf8');
        for (const [pattern, label] of FORBIDDEN_PATTERNS) {
          if (pattern.test(src)) violations.push(`${rel}: ${label}`);
        }
      }
    }

    expect(violations).toEqual([]);
  });

  it('keeps component motion on semantic presets and the shared Spinner', () => {
    const violations: string[] = [];
    let loader2Count = 0;
    let animateSpinCount = 0;

    for (const root of SOURCE_ROOTS) {
      for (const file of collectMotionTsxFiles(join(process.cwd(), root))) {
        const rel = relative(process.cwd(), file);
        const src = readFileSync(file, 'utf8');
        for (const [pattern, label] of MOTION_FORBIDDEN_PATTERNS) {
          pattern.lastIndex = 0;
          const hits = [...src.matchAll(pattern)].map(match => match[0]);
          if (hits.length > 0) violations.push(`${rel}: ${label} (${[...new Set(hits)].join(', ')})`);
        }
        if (/from ["']motion\/react["']/.test(src)) violations.push(`${rel}: motion/react import`);

        const fileLoaderCount = src.match(/\bLoader2\b/g)?.length ?? 0;
        const fileSpinCount = src.match(/\banimate-spin\b/g)?.length ?? 0;
        if (rel !== SPINNER_FILE && fileLoaderCount > 0) violations.push(`${rel}: Loader2 outside ${SPINNER_FILE}`);
        if (rel !== SPINNER_FILE && fileSpinCount > 0) violations.push(`${rel}: animate-spin outside ${SPINNER_FILE}`);
        loader2Count += fileLoaderCount;
        animateSpinCount += fileSpinCount;
      }
    }

    expect(violations).toEqual([]);
    expect(loader2Count).toBe(3);
    expect(animateSpinCount).toBe(1);

    const spinner = readFileSync(join(process.cwd(), SPINNER_FILE), 'utf8');
    expect(spinner).toContain("'motion-essential animate-spin shrink-0'");
    expect(spinner).toContain("sm: 'size-3.5'");
    expect(spinner).toContain("md: 'size-4'");
    expect(spinner).toContain("lg: 'size-5'");
  });

  it('keeps CSS-first motion foundations, presets, and reduced-motion policy canonical', () => {
    const globals = readFileSync(join(process.cwd(), 'app/globals.css'), 'utf8');
    const registrations = [
      '--animate-overlay-in:', '--animate-overlay-out:', '--animate-pop-in:', '--animate-pop-out:',
      '--animate-menu-in:', '--animate-menu-out:', '--animate-sheet-in:', '--animate-sheet-out:',
      '--animate-toast-in:', '--animate-toast-out:', '--animate-reveal:',
    ];
    const utilities = [
      '@utility transition-feedback', '@utility transition-toggle',
      '@utility transition-layout', '@utility transition-progress', '@utility motion-essential',
    ];

    expect(globals).toContain('--transition-duration-fast: 120ms;');
    expect(globals).toContain('--transition-duration-base: 180ms;');
    expect(globals).toContain('--transition-duration-slow: 240ms;');
    expect(globals).toContain('--transition-duration-progress: 500ms;');
    expect(globals).toContain('--ease-*: initial;');
    for (const registration of registrations) expect(globals).toContain(registration);
    for (const utility of utilities) expect(globals).toContain(utility);
    expect(globals).toMatch(/@media \(prefers-reduced-motion: reduce\) \{[\s\S]*animation-duration: 0\.01ms !important;[\s\S]*transition-duration: 0\.01ms !important;/);
    expect(globals).not.toContain('@plugin "tailwindcss-animate"');
    expect(globals).not.toMatch(/--duration-(?:fast|base|slow)|goldShimmer|@keyframes slideIn|@keyframes fade-in/);

    const foreignKeyframes: string[] = [];
    for (const root of SOURCE_ROOTS) {
      for (const file of collectMotionSourceFiles(join(process.cwd(), root))) {
        const rel = relative(process.cwd(), file);
        if (rel !== 'app/globals.css' && readFileSync(file, 'utf8').includes('@keyframes')) foreignKeyframes.push(rel);
      }
    }
    expect(foreignKeyframes).toEqual([]);
  });

  it('keeps Radix surfaces on their fixed semantic motion pairings', () => {
    const dialog = readFileSync(join(process.cwd(), 'components/ui/dialog.tsx'), 'utf8');
    expect(dialog).toContain('data-[state=open]:animate-overlay-in data-[state=closed]:animate-overlay-out');
    expect(dialog).toContain('data-[state=open]:animate-pop-in data-[state=closed]:animate-pop-out');

    const sheet = readFileSync(join(process.cwd(), 'components/ui/sheet.tsx'), 'utf8');
    expect(sheet).toContain('data-[state=closed]:animate-sheet-out data-[state=open]:animate-sheet-in');
    expect(sheet).toContain('data-motion-side={side}');

    for (const rel of [
      'components/ui/dropdown-menu.tsx',
      'components/ui/popover.tsx',
      'components/ui/tooltip.tsx',
      'components/ui/select.tsx',
    ]) {
      const src = readFileSync(join(process.cwd(), rel), 'utf8');
      expect(src).toContain('animate-menu-in');
      expect(src).toContain('animate-menu-out');
    }

    const command = readFileSync(join(process.cwd(), 'components/ui/command.tsx'), 'utf8');
    expect(command).toContain("from '@/components/ui/dialog'");
    expect(command).toContain('<DialogContent');
  });

  it('keeps raw visual-value debt from growing', () => {
    const counts: Record<keyof typeof VISUAL_DEBT_BASELINE, number> = {
      arbitraryShadow: 0,
      arbitraryText: 0,
      arbitraryTracking: 0,
      hexColor: 0,
      inlineStyle: 0,
      rgba: 0,
    };

    for (const root of SOURCE_ROOTS) {
      for (const file of collectUiSourceFiles(join(process.cwd(), root))) {
        const src = readFileSync(file, 'utf8');
        for (const [label, pattern] of VISUAL_DEBT_PATTERNS) {
          pattern.lastIndex = 0;
          counts[label] += [...src.matchAll(pattern)].length;
        }
      }
    }

    expect(counts).toEqual(VISUAL_DEBT_BASELINE);
  });

  it('keeps business UI off bare Tailwind palette utilities (semantic tokens only)', () => {
    const violations: string[] = [];

    for (const root of SOURCE_ROOTS) {
      for (const file of collectTsxFiles(join(process.cwd(), root))) {
        const rel = relative(process.cwd(), file);
        if (NAMED_PALETTE_EXEMPT_PREFIXES.some(prefix => rel.startsWith(prefix))) continue;
        const src = readFileSync(file, 'utf8');
        NAMED_PALETTE_PATTERN.lastIndex = 0;
        const hits = [...src.matchAll(NAMED_PALETTE_PATTERN)].map(m => m[0]);
        if (hits.length > 0) violations.push(`${rel}: ${[...new Set(hits)].join(', ')}`);
      }
    }

    expect(violations).toEqual([]);
  });

  it('keeps removed SaaS product surfaces out of business UI', () => {
    const violations: string[] = [];

    for (const root of SOURCE_ROOTS) {
      for (const file of collectTsxFiles(join(process.cwd(), root))) {
        const rel = relative(process.cwd(), file);
        const src = readFileSync(file, 'utf8');
        for (const [pattern, label] of LEGACY_PRODUCT_PATTERNS) {
          if (pattern.test(src)) violations.push(`${rel}: ${label}`);
        }
      }
    }

    expect(violations).toEqual([]);
  });

  // INV-DD-01 — shape follows semantic role, not the call site.
  it('keeps business Button call sites on the canonical Button radius', () => {
    const violations: string[] = [];
    let stagePillExceptionCount = 0;

    for (const root of SOURCE_ROOTS) {
      for (const file of collectTsxFiles(join(process.cwd(), root))) {
        const rel = relative(process.cwd(), file);
        const src = readFileSync(file, 'utf8');
        for (const tag of openingTags(src, 'Button')) {
          if (tag.includes(RADIUS_EXCEPTION_ATTR)) {
            // The one documented pill exception, pinned to its owning file.
            stagePillExceptionCount++;
            if (rel !== RADIUS_EXCEPTION_FILE) {
              violations.push(`${rel}: stage-pill radius exception used outside ${RADIUS_EXCEPTION_FILE}`);
            }
            if (!RADIUS_PATTERN.test(classSources(tag, src))) {
              violations.push(`${rel}: stage-pill exception has no explicit pill radius`);
            }
            continue;
          }
          const sources = classSources(tag, src);
          if (sources.includes('__unresolved_class_source:')) {
            violations.push(`${rel}: Button radius cannot be verified because a class source is unresolved`);
          }
          const match = sources.match(RADIUS_PATTERN);
          if (match) violations.push(`${rel}: Button overrides radius (${match[0]})`);
        }
      }
    }

    expect(stagePillExceptionCount).toBe(1);
    expect(violations).toEqual([]);
  });

  // INV-DD-01 — the stop-stream role exposes exactly one shape.
  it('keeps the stop-stream control on a single shape', () => {
    const primitive = readFileSync(join(process.cwd(), 'components/ui/StopStreamingButton.tsx'), 'utf8');

    // No `shape` prop, no shape lookup table, no radius of its own.
    expect(primitive).not.toMatch(/\bshape\s*[?:=]/);
    expect(primitive).not.toMatch(RADIUS_PATTERN);
    expect(primitive).not.toMatch(/\bclassName\??:/);
    expect(primitive).toContain('size="unstyled"');
    expect(primitive).toContain("fullWidth && 'w-full py-2.5'");

    const forkedCallers: string[] = [];
    for (const root of SOURCE_ROOTS) {
      for (const file of collectTsxFiles(join(process.cwd(), root))) {
        const rel = relative(process.cwd(), file);
        const src = readFileSync(file, 'utf8');
        for (const tag of openingTags(src, 'StopStreamingButton')) {
          if (/\bshape=|\bclassName=/.test(tag) || RADIUS_PATTERN.test(tag)) {
            forkedCallers.push(`${rel}: stop-stream call site re-shapes the control`);
          }
        }
      }
    }

    expect(forkedCallers).toEqual([]);
  });

  // INV-DD-02 — manuscript page-turn navigation stays on one shared primitive.
  it('routes book page-turn navigation through the shared primitive', () => {
    const violations: string[] = [];

    for (const rel of PAGE_TURN_SURFACES) {
      const src = readFileSync(join(process.cwd(), rel), 'utf8');
      if (!src.includes(PAGE_TURN_PRIMITIVE)) violations.push(`${rel}: does not import ${PAGE_TURN_PRIMITIVE}`);
      if (!src.includes('<PageTurnButton')) violations.push(`${rel}: does not render PageTurnButton`);
    }

    // The round-nav class signature may only exist inside the primitive.
    for (const root of SOURCE_ROOTS) {
      for (const file of collectTsxFiles(join(process.cwd(), root))) {
        const rel = relative(process.cwd(), file);
        const src = readFileSync(file, 'utf8');
        if (PAGE_TURN_SIGNATURE.test(src)) violations.push(`${rel}: hand-rolled round page-turn control`);
      }
    }

    expect(violations).toEqual([]);
  });

  it('keeps manuscript notices and flipbook sizing on their canonical contracts', () => {
    const reading = readFileSync(join(process.cwd(), 'components/ManuscriptReadingView.tsx'), 'utf8');
    const pagination = readFileSync(join(process.cwd(), 'hooks/useDynamicPagination.ts'), 'utf8');
    const geometry = readFileSync(join(process.cwd(), 'lib/flipbook-geometry.ts'), 'utf8');
    const globals = readFileSync(join(process.cwd(), 'app/globals.css'), 'utf8');
    const workspace = readFileSync(join(process.cwd(), 'components/NovelWorkspace.tsx'), 'utf8');
    const noticeStart = workspace.indexOf('function ManuscriptNoticeRow');
    const noticeEnd = workspace.indexOf('/**', noticeStart + 1);
    const notice = workspace.slice(noticeStart, noticeEnd);

    expect(reading).toContain('autoSize={false}');
    expect(reading).toContain('width={FLIPBOOK_LAYOUT.pageWidth}');
    expect(reading).toContain('height={FLIPBOOK_LAYOUT.pageHeight}');
    expect(reading).not.toContain('maxHeight=');
    expect(pagination).toContain('computeFlipbookGeometry(el.clientWidth, el.clientHeight)');
    expect(geometry).toContain('pageWidth: 500');
    expect(geometry).toContain('pageHeight: 850');
    expect(globals).toMatch(/\.manuscript-flipbook\s*\{[^}]*height:\s*100%[^}]*width:\s*100%/);
    expect(notice).toContain('rounded-lg');
    expect(notice).not.toContain('rounded-full');
  });

  // INV-DD-03 — content-level empty states use the Empty family; loading and
  // error stay separately identifiable.
  it('keeps audited content surfaces on the Empty primitive', () => {
    const violations: string[] = [];

    for (const rel of EMPTY_STATE_SURFACES) {
      const src = readFileSync(join(process.cwd(), rel), 'utf8');
      if (!src.includes(EMPTY_PRIMITIVE)) violations.push(`${rel}: does not import ${EMPTY_PRIMITIVE}`);
      if (!src.includes('<Empty')) violations.push(`${rel}: does not render Empty`);
      const emptyTags = openingTags(src, 'Empty');
      if (!emptyTags.some(tag => hasClassTokens(tag, src, EMPTY_DENSITY_CONTRACTS[rel]))) {
        violations.push(`${rel}: Empty density contract drifted`);
      }
      if (hasAdHocEmptyWrapper(src)) violations.push(`${rel}: ad-hoc centered empty-state wrapper`);
    }

    // Loading and error are their own branches — an Empty must never be the
    // only thing these surfaces can render while busy or broken.
    const list = readFileSync(join(process.cwd(), 'components/conversations/ConversationList.tsx'), 'utf8');
    expect(list).toMatch(/loading && conversations\.length === 0/);
    expect(list).toMatch(/\{error && \(/);

    const thread = readFileSync(join(process.cwd(), 'components/conversations/ConversationThread.tsx'), 'utf8');
    expect(thread).toMatch(/loading \?[\s\S]{0,200}Spinner/);

    const usage = readFileSync(join(process.cwd(), 'components/studio/usage-panel.tsx'), 'utf8');
    expect(usage).toMatch(/\{error && \(/);
    expect(usage).toMatch(/!error && !loading && !hasData/);

    const knowledge = readFileSync(join(process.cwd(), 'components/knowledge/KnowledgePanel.tsx'), 'utf8');
    expect(knowledge).toMatch(/loading && !entries\.length/);

    expect(violations).toEqual([]);
  });

  // INV-DD-04 — a compact model-status control must read as actionable.
  it('keeps compact writing-model status controls visibly actionable', () => {
    const rel = 'components/WritingModelStatusBar.tsx';
    const src = readFileSync(join(process.cwd(), rel), 'utf8');
    const violations: string[] = [];

    for (const element of elements(src, 'Button')) {
      const [tag = element] = openingTags(element, 'Button');
      if (RADIUS_PATTERN.test(classSources(tag, src))) {
        violations.push(`${rel}: model-status control overrides radius (status-badge geometry)`);
      }
      // Every clickable control here opens model settings — it carries the
      // settings affordance so it cannot be mistaken for a passive badge.
      if (!element.includes('Settings2')) {
        violations.push(`${rel}: model-status control has no Settings2 affordance`);
      }
    }

    expect(violations).toEqual([]);
    expect(src).toContain('Settings2');
    const mountPlaceholder = src.slice(src.indexOf('// Server + first client render'), src.indexOf('if (!bound)'));
    const [compactPlaceholder = ''] = openingTags(mountPlaceholder, 'span');
    expect(compactPlaceholder).toContain('rounded-md');
    expect(compactPlaceholder).not.toContain('rounded-full');
  });

});
